### ISSUE TITLE
subtract() broken?

### ISSUE THREAD

**Issue by relu-xz** [sedran/moment4j#3]
I wanna get the date of 30 days ago and this simply does not work:

`Moment.moment().subtract(30, Calendar.DAY_OF_MONTH).format("dd/mm/yyyy");`

It returns:

`22/51/2019`

**Comment by sedran** [comment]
Hello @zorobabel ;

Moment4j simply uses `java.text.SimpleDateFormat` to convert dates to string. The format that you have given and your expectation do not match because "mm" means minute for `SimpleDateFormat`.

If you need month, you should use capital letters: "MM"

Example Date Format: "yyyy-MM-dd HH:mm:ss.SSS"

For your case, this should work: "dd/MM/yyyy"

**Comment by relu-xz** [comment]
Hi @sedran!

What a mistake, thank you!
